name: CI Pipeline

on:
  schedule:
    - cron: "41 * * * *"
  workflow_dispatch:

concurrency:
  group: osv-rules-ci
  cancel-in-progress: false

jobs:
  generate:
    strategy:
      matrix:
        ecosystem: [npm, pypi, nuget, maven]
    uses: ./.github/workflows/_osv_rulegen.yml
    with:
      ecosystem: ${{ matrix.ecosystem }}
      rulesets_dir: rulesets

  commit:
    needs: generate
    permissions:
      contents: write
    uses: ./.github/workflows/_commit.yml
    with:
      rulesets_dir: rulesets
    secrets:
      app_id: ${{ secrets.APP_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
